{
 "title": "Main Dashboard",
 "description": "Eve Market Browser Main Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Store Status",
   "type": "state-timeline",
   "description": "Dispaly store status",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "up", "legendFormat": "Store running" },
    { "expr": "store_order_status_info", "legendFormat": "Orders up to date" },
    { "expr": "store_history_status_info", "legendFormat": "Histories up to date" }
   ]
  },
  {
   "title": "Esi Requests",
   "type": "timeseries",
   "description": "The number of requests per seconds",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(result) (rate(store_esi_request_total[1m]))",
     "legendFormat": "{{result}}"
    }
   ]
  },
  { "title": "Erros", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Esi Errors",
   "type": "timeseries",
   "description": "Display the rate of esi errors per seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "rate(store_esi_error_total[$__rate_interval])",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Worker Errors",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    { "expr": "store_worker_error_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Store Memory",
   "type": "timeseries",
   "description": "Graph ram resources for the esi data store",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes / 1000000",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Store CPU",
   "type": "timeseries",
   "description": "Graph cpu resources used by the esi data store",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "cpus/m" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "CPU usage"
    }
   ]
  }
 ]
}